northwind:
  outputs:
    dev:
      dbname: northwind
      host: localhost
      pass: admin
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev
